// Generated by CoffeeScript 1.7.1
var through;

through = require('through');

module.exports = function(_arg) {
  var filter, map, originalMap;
  map = _arg.map, filter = _arg.filter;
  if (filter == null) {
    filter = function() {
      return true;
    };
  }
  if (map.length !== 3) {
    originalMap = map;
    map = function(filepath, data, callback) {
      var e;
      try {
        return callback(null, originalMap(filepath, data));
      } catch (_error) {
        e = _error;
        return callback(e);
      }
    };
  }
  return function(filepath) {
    var data, end, write;
    data = '';
    write = function(chunk) {
      return data += chunk;
    };
    end = function() {
      return map(filepath, data, (function(_this) {
        return function(err, data) {
          if (err != null) {
            return _this.emit('error', err);
          } else {
            _this.queue(data);
            return _this.queue(null);
          }
        };
      })(this));
    };
    if (filter(filepath)) {
      return through(write, end);
    } else {
      return through();
    }
  };
};
